version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - appNetwork
  msspecialty:
    build:
      context: ./MSSpeciality
    ports:
      - "8086:8086"
    volumes:
      - ./MSSpeciality:/usr/src/app
    depends_on:
      - elasticsearch
      - fluentd
    networks:
      - appNetwork
  msauth:
    build:
      context: ./MSAuth
    ports:
      - "8081:8081"
    volumes:
      - ./MSAuth:/usr/src/app
    depends_on:
      - elasticsearch
      - fluentd
    networks:
      - appNetwork
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - appNetwork

  fluentd:
    image: fluent/fluentd:v1.10-1
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/logs:/fluentd/log
    networks:
      - appNetwork
networks:
  appNetwork:
    driver: bridge

volumes:
  mongo-data: